reduce number of timeout

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -29,26 +29,27 @@ jobs:
           node ./scripts/send_sms.js 
 
       - name: Wait for SMS Approval
-        timeout-minutes: 15
+        timeout-minutes: 10
         run: |
-         approved=false
-         while [ "$approved" = false ]; do
-          set +e  # Disable immediate exit on non-zero status
-          node ./scripts/check_sms_approval.js
-          exit_code=$?
+          approved=false
+          while [ "$approved" = false ]; do
+            set +e  # Disable immediate exit on non-zero status
+            node ./scripts/check_sms_approval.js
+            exit_code=$?
       
-          if [ $exit_code -eq 0 ]; then
-            approved=true  # Approval received
-          elif [ $exit_code -eq 2 ]; then
-            echo "Approval rejected. Exiting..."
-            exit 1  # Exit with failure if approval is rejected
-          else
-            echo "Waiting for approval..."
-            sleep 60  # Wait for 1 minute before checking again
-          fi
+            if [ $exit_code -eq 0 ]; then
+             echo "Both approvals received. Proceeding..."
+             approved=true  # Approval received, proceed
+            elif [ $exit_code -eq 2 ]; then
+             echo "Approval rejected. Exiting..."
+             exit 1  # Exit with failure if approval is rejected
+            else
+             echo "Still waiting for approval..."
+             sleep 15  # Wait for 1 minute before checking again
+            fi
 
-          set -e  # Re-enable immediate exit after node command
-         done
+            set -e  # Re-enable immediate exit after node command
+          done
  
       - name: Deploy the Application via Render Deploy Hook
         if: success() 
